language: ruby
rvm:
- 2.1

script: ./_bin/cibuild

branches:
  only:
  - gh-pages
  - /^greenkeeper/.*$/

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
